#pragma config(Motor,  port1,           leftmotor,     tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port9,           sideway,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Arcade Drive: Horizontal

task main()
{
	while (1==1) {
		motor[leftmotor]=63;
		motor[rightmotor]=63;
		wait1Msec(3000);
		motor[leftmotor]=0;
		motor[rightmotor]=0; //repeat
		wait1Msec(3000);
	}


}
