#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  limitswitch,    sensorTouch)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port9,           sideway,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	motor[rightmotor] = 63;
	motor[leftmotor] = 63;
	motor[sideway] = 63;
	wait10Msec(200);
	motor[rightmotor] = 0;
	motor[leftmotor] = 0;
	motor[sideway] = 0;
	wait10Msec(200);
	while(1==1)
	{
		if((SensorValue(sonar) < 40 && SensorValue(sonar) > 0) || SensorValue(limitswitch) != 0 || SensorValue(potentiometer) <= 200) {
			motor[rightmotor] = 0;
			motor[leftmotor] = 0;
			motor[sideway] = 0;
		}
		else {
			motor[rightmotor]  = (vexRT[Ch2] + vexRT[Ch1]); // Vertical + Horizontal (Left side)
			motor[leftmotor] = (vexRT[Ch2] - vexRT[Ch1]); // Vertical - Horizontal (Right side)
			motor[sideway] = (vexRT[Ch4]); // Controls side wheel



		}
	}
}
