#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_cm)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port9,           sideway,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Sonar sensor sample program

task main()
{
	while (1==1)
	{
	while (SensorValue(sonar) > 40 || SensorValue(sonar) <= 0) {
		motor [sideway] = 63;

	}
motor(sideway) = 0;
}
}
