#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port7,           sideway,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1==1)
	{
		motor[leftmotor] = vexRT(Ch3);
		motor[rightmotor] = vexRT(Ch2);

		motor[sideway] = vexRT(Btn6U) * 127;

		motor[sideway] = vexRT(Btn5U) * -127;
	}

}
