#pragma config(Sensor, dgtl1,  limitswitch1,   sensorTouch)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port9,           sideway,       tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		wait1Msec(100);
  	if(SensorValue(limitswitch1) == 1)
  	{
    	motor[rightmotor] = 63;
    	motor[leftmotor]  = 63;
		}
		else
		{
			motor[rightmotor] = 0;
    	motor[leftmotor]  = 0;
		}
	}
}
